[package]
name = "nineteen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.4.2"
env_logger = "0.10.0"
log = "0.4.17"
