[package]
name = "twenty-two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
nalgebra = "0.32.2"
itertools = "0.10.5"
typed-arena = "2.0.2"
